package net.kollnig.missioncontrol.wg

import android.net.VpnService
import android.os.ParcelFileDescriptor
import android.util.Log
import net.kollnig.missioncontrol.wgbridge.Logger as WgLogger
import net.kollnig.missioncontrol.wgbridge.Protector as WgProtector
import net.kollnig.missioncontrol.wgbridge.Tunnel as WgTunnel
import net.kollnig.missioncontrol.wgbridge.Wgbridge

/**
 * Owns the wireguard-go tunnel that sits behind NetGuard's IP-layer hijack.
 *
 * Lifecycle is driven by [startOrUpdate] from `ServiceSinkhole.startNative`
 * and [stop] from the actual VPN-shutdown path. Crucially, `stopNative` does
 * NOT call [stop] — when NetGuard does a "Native restart" reload (same
 * builder, same TUN fd) we want WG to keep running so we don't redo the
 * handshake on every DHCP/connectivity blip.
 *
 * The wgbridge classes used here are generated by `gomobile bind`; build
 * instructions live in `wgbridge/README.md`.
 */
object WgEgress {
    private const val TAG = "WgEgress"
    private const val DEFAULT_MTU = 1420

    @Volatile private var tunnel: WgTunnel? = null
    private var currentConfig: String? = null
    private var currentTunFd: Int = -1

    /**
     * Bring the tunnel up, take it down, or leave it alone — whichever the
     * desired state requires. Idempotent: same config + same TUN fd is a
     * no-op so reload-induced restarts don't re-handshake.
     *
     * Returns true on success or already-correct state. Returns false if
     * WG was supposed to start but failed; in that case the C side is left
     * with `wg_enabled = 0` so traffic isn't black-holed (fail-closed
     * applies only when WG is *running* and traffic should be protected).
     */
    fun startOrUpdate(
        wgEnabled: Boolean,
        configText: String?,
        vpnService: VpnService,
        vpnFd: ParcelFileDescriptor,
        startSocketpair: () -> Int,
        stopSocketpair: () -> Unit
    ): Boolean {
        val wantRunning = wgEnabled && !configText.isNullOrEmpty()
        val desiredFd = vpnFd.fd

        if (!wantRunning) {
            if (tunnel != null) {
                Log.i(TAG, "WG disabled — tearing down tunnel")
                stopInternal(stopSocketpair)
            }
            return true
        }

        if (tunnel != null && currentConfig == configText && currentTunFd == desiredFd) {
            Log.v(TAG, "startOrUpdate: same config + same TUN fd, no-op")
            return true
        }

        if (tunnel != null) {
            Log.i(TAG, "WG config or TUN fd changed — restarting")
            stopInternal(stopSocketpair)
        }

        val parsed = try {
            WgConfigParser.parse(configText!!)
        } catch (e: Exception) {
            Log.e(TAG, "config parse: ${e.message}")
            return false
        }

        val resolved = try {
            withResolvedEndpoints(parsed)
        } catch (e: Exception) {
            Log.e(TAG, "endpoint resolve: ${e.message}")
            return false
        }

        val rxFd = startSocketpair()
        if (rxFd < 0) {
            Log.e(TAG, "jni_wireguard_start failed")
            return false
        }

        val mtu = resolved.mtu ?: DEFAULT_MTU
        val protector = object : WgProtector {
            override fun protect(fd: Int): Boolean = vpnService.protect(fd)
        }
        val logger = object : WgLogger {
            override fun verbosef(s: String) { Log.v(TAG, s) }
            override fun errorf(s: String)   { Log.e(TAG, s) }
        }

        try {
            tunnel = Wgbridge.startTunnel(
                resolved.toUapi(), rxFd, desiredFd, mtu, protector, logger
            )
        } catch (e: Throwable) {
            Log.e(TAG, "Wgbridge.startTunnel failed", e)
            stopSocketpair()
            return false
        }

        currentConfig = configText
        currentTunFd = desiredFd
        Log.i(TAG, "WG up: tunFd=$desiredFd mtu=$mtu peers=${resolved.peers.size}")
        return true
    }

    /** Tear down the tunnel completely. Called on actual service stop. */
    fun stop(stopSocketpair: () -> Unit) {
        if (tunnel != null) stopInternal(stopSocketpair)
    }

    fun isRunning(): Boolean = tunnel != null

    private fun stopInternal(stopSocketpair: () -> Unit) {
        val t = tunnel
        tunnel = null
        currentConfig = null
        currentTunFd = -1
        if (t != null) {
            try {
                t.stop()
            } catch (e: Throwable) {
                Log.w(TAG, "tunnel.stop threw", e)
            }
        }
        stopSocketpair()
    }

    private fun withResolvedEndpoints(config: WgConfig): WgConfig {
        return config.copy(peers = config.peers.map { peer ->
            val ep = peer.endpoint
            if (ep == null) peer else peer.copy(endpoint = resolveEndpoint(ep))
        })
    }

    /**
     * "host:port" or "[v6-host]:port" -> "ip:port" or "[ip]:port".
     * Hostname is resolved synchronously; caller must run off the main thread.
     */
    private fun resolveEndpoint(endpoint: String): String {
        val (host, port) = if (endpoint.startsWith("[")) {
            val close = endpoint.indexOf(']')
            require(close > 0 && endpoint.length > close + 2 && endpoint[close + 1] == ':') {
                "malformed IPv6 endpoint: $endpoint"
            }
            endpoint.substring(1, close) to endpoint.substring(close + 2)
        } else {
            val colon = endpoint.lastIndexOf(':')
            require(colon > 0 && colon < endpoint.length - 1) {
                "missing :port in endpoint: $endpoint"
            }
            endpoint.substring(0, colon) to endpoint.substring(colon + 1)
        }
        val addr = java.net.InetAddress.getByName(host)
        val ip = addr.hostAddress ?: throw IllegalStateException("getHostAddress null for $host")
        return if (addr is java.net.Inet6Address) "[$ip]:$port" else "$ip:$port"
    }
}
