/*
 * Hand-written JNI binding to the Rust wgbridge library (wgbridge-rs/),
 * which embeds gotatun, Mullvad's WireGuard implementation. This package
 * replaces the classes previously generated by gomobile bind; the API shape
 * is kept identical so call sites did not have to change.
 */
package net.kollnig.missioncontrol.wgbridge;

public final class Wgbridge {
    static {
        System.loadLibrary("wgbridge");
    }

    private Wgbridge() {
    }

    /**
     * Returns a fresh base64 WireGuard private key.
     */
    public static native String generatePrivateKey();

    /**
     * Derives the base64 WireGuard public key for a base64 private key.
     */
    public static native String publicKey(String privateKey);

    /**
     * Boots gotatun.
     *
     * @param uapiConfig   UAPI text produced by WgConfig.toUapi()
     * @param outboundRxFd read end of a socketpair held by C; C writes raw IP
     *                     packets, the bridge reads them and feeds gotatun
     * @param tunWriteFd   VpnService TUN fd; decrypted inbound IP packets are
     *                     written here
     * @param mtu          payload MTU (typically 1420)
     * @param protector    callback to VpnService.protect(int)
     * @param logger       callback for bridge log lines (may be null)
     * @param dnsRecorder  callback for passive DNS answer recording (may be null)
     *
     * The supplied fds are duplicated; Tunnel.stop() closes only the duplicates.
     */
    public static Tunnel startTunnel(String uapiConfig, int outboundRxFd, int tunWriteFd, int mtu,
                                     Protector protector, Logger logger, DnsRecorder dnsRecorder) {
        long handle = nativeStartTunnel(uapiConfig, outboundRxFd, tunWriteFd, mtu,
                protector, logger, dnsRecorder);
        return new Tunnel(handle);
    }

    private static native long nativeStartTunnel(String uapiConfig, int outboundRxFd, int tunWriteFd,
                                                 int mtu, Protector protector, Logger logger,
                                                 DnsRecorder dnsRecorder);
}
