name: Validate Fastlane metadata

on:
  push:
    branches: [ master, main ]
    paths: [ 'fastlane/**' ]
  pull_request:
    branches: [ master, main ]
    paths: [ 'fastlane/**' ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          fastlaneDir: ./fastlane/metadata/android
